site_name: COMP423 Course Notes
theme:
  name: material
  icon:
    admonition:
      quote: octicons/quote-16
      info: octicons/info-16
      question: octicons/question-16
      tip: octicons/squirrel-16
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables